### ISSUE TITLE
Tutorial and Usage is wrong

### ISSUE THREAD

**Issue by AlisterH** [Asugawara/requests-html-playwright#19]
Following the example in Tutorial & Usage doesn't work, so either the docs are out of date or something is broken:
```
import requests_html_playwright
from requests_html_playwright import HTMLSession
Traceback (most recent call last):
  File "D:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
ImportError: cannot import name 'HTMLSession' from 'requests_html_playwright' (D:\OSGeo4W\apps\Python39\lib\site-packages\requests_html_playwright\__init__.py)
```
I need to access `HTMLSession()` like this:
```
from requests_html_playwright import requests_html
session = requests_html.HTMLSession()
r = session.get('https://python.org/')
r.html.url
'https://www.python.org/'
```

**Comment by Asugawara** [comment]
Thank you for reporting the issue, and apologies for the late response!
The issue has been resolved!
https://github.com/Asugawara/requests-html-playwright/pull/20
